/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class PrivateClass */

#ifndef _Included_PrivateClass
#define _Included_PrivateClass
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
